default:
  directory: "~/R Language Default Dir/Github-projects/multiview-oneclass/"
  conda_env: "r-reticulate"
  source_scripts: "R/load-packages.R"
  path_to_save_derived_datasets: "data/derived-data"
  OC_combined_experiments: "/OC_Combined/"
  path_to_read_datasets: "data/derived-data"
  

production:
  directory: "~/GitHub_projects/multiview-oneclass/"
  source_scripts: "R/load-packages.R"
  path_to_save_derived_datasets: "~/Downloads/DAMI_datasets/derived_data"
  OC_combined_experiments: "/OC_Combined/"
  path_to_read_datasets: "~/Downloads/DAMI_datasets/derived_data"
  
